steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd cython
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      terraform init || exit 1

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd cython
      echo ""
      echo "*************** TERRAFORM PLAN ******************"
      terraform plan || exit 1
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ "x$BRANCH_NAME/" == "xprod" ]; then
        cd cython
        echo ""
        echo "*************** TERRAFORM PLAN ******************"
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' is not prod."
        echo "*******************************************************************************"
      fi
# [END tf-apply]